export const GET_ALL_CATEGORY ="GET_ALL_CATEGORY"

export const GET_ONE_CATEGORY ="GET_ONE_CATEGORY"

export const GET_ERROR ="GET_ERROR"

export const CREATE_CATEGORY ="CREATE_CATEGORY"

export const CREATE_PRODUCT ="CREATE_PRODUCT"

export const GET_ALL_PRODUCTS ="GET_ALL_PRODUCTS"

export const GET_ONE_PRODUCT ="GET_ONE_PRODUCT"

export const GET_SMILAR_PRODUCT ="GET_SMILAR_PRODUCT"

export const DELETE_PRODUCT ="DELETE_PRODUCT"

export const UPDATE_PRODUCT ="UPDATE_PRODUCT"

export const GET_ALL_BRAND ="GET_ALL_GET_ALL_BRAND"

export const GET_ONE_BRAND ="GET_ONE_BRAND"

export const CREATE_BRAND ="CREATE_BRAND"

export const CREATE_SUB_CATEGORY ="CREATE_SubCATEGORY"

export const GET_SUB_CATEGORY ="GET_SUB_CATEGORY"

export const CREATE_NEW_USER ="CREATE_NEW_USER"

export const LOGIN_USER ="LOGIN_USER"

export const FORGET_PASSWORD ="FORGET_PASSWORD"

export const VERIFY_PASSWORD ="VERIFY_PASSWORD"

export const RESET_PASSWORD ="RESET_PASSWORD"

export const CREATE_REVIEW ="CREATE_REVIEW"

export const GET_ALL_REVIEWS ="GET_ALL_REVIEWS"

export const DELETE_REVIEW ="DELETE_REVIEW"

export const EDIT_REVIEW ="EDIT_REVIEW"

export const ADD_TO_WISHLIST ="ADD_TO_WISHLIST"

export const REMOVE_FROM_WISHLIST ="REMOVE_FROM_WISHLIST"

export const USER_WISHLIST ="GET_PRODUCTS_WISH_LIST"

export const ADD_COUPON ="ADD_COUPON"

export const GET_ALL_COUPONS ="GET_ALL_COUPONS"

export const DELETE_COUPON ="DELETE_COUPON"

export const GET_ONE_COUPON ="GET_ONE_COUPON"

export const EDIT_COUPON ="EDIT_COUPON"

export const ADD_USER_ADDRESS ="ADD_USER_ADDRESS"

export const VIEW_ADDRESS ="VIEW_ADDRESS"

export const DELETE_ADDRESS ="DELETE_ADDRESS"

export const GET_ONE_ADDRESS ="GET_ONE_ADDRESS"


export const UPDATE_ADDRESS ="UPDATE_ADDRESS"

export const UPDATE_USER_DATA ="UPDATE_USER_DATA"

export const UPDATE_USER_PASSWORD ="UPDATE_USER_PASSWORD"

export const ADD_TO_CART = "ADD_TO_CART"

export const GET_ALL_PRODUCTS_CART = "GET_ALL_PRODUCTS_CART"

export const DELETE_ALL_PRODUCTS_CART = "DELETE_ALL_PRODUCTS_CART"

export const DELETE_ONE_PRODUCT_CART = "DELETE_ONE_PRODUCT_CART"

export const UPDATE_ONE_PRODUCT_CART = "UPDATE_ONE_PRODUCT_CART"

export const APPLY_COUPON_TO_CART = "APPLY_COUPON_TO_CART"

export const PRODUCTS_BY_CATEGORY = "PRODUCTS_BY_CATEGORY"

export const PRODUCTS_BY_BRAND = "PRODUCTS_BY_BRAND"

export const CREATE_CASH_ORDER = "CREATE_CASH_ORDER"

export const  GET_USER_ORDERES = "GET_USER_ORDERES"


export const  GET_ONE_ORDER = "GET_ONE_ORDER"

export const  UPDAE_ORDER_PAY = "UPDAE_ORDER_PAY"

export const  UPDAE_ORDER_DELIVER = "UPDAE_ORDER_DELIVER"

export const  CREATE_CARD_ORDER = "CREATE_CARD_ORDER"





